variable "COMPONENT" {}
variable "ENV" {}
variable "INSTANCE_CLASS" {}
variable "ENGINE" {}
variable "SUBNET_IDS" {}
variable "FAMILY" {}
variable "SKIP_FINAL_SNAPSHOT" {}
variable "NODE_COUNT" {}
variable "VPC_ID" {}
variable "CIDR_BLOCK" {}
variable "AZ" {}
variable "ENGINE_VERSION" {}
variable "DB_NAME" {}
variable "WORKSTATION_IP" {}
